

#端口号
server:
    port: 8880
   
    
#thymeleaf  and redis 配置 session 失效时间 20分钟
spring:
   profiles:
       active: test

   http: 
      multipart:
          max-file-size: 10MB
          max-request-size: 10MB

# MyBatis配置
mybatis:
    typeAliasesPackage: com.fq
    mapperLocations: classpath:/sqlmaps/**/*.xml
    configLocation: classpath:/mybatis-config.xml
    

