
spring: 
   redis: 
        database: 2
        host: 47.93.200.92
        password: freeredisZAQ!
        port: 6379
   session: 
        timeout: 7200
   http: 
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB


# 数据源配置
spring:
      datasource:
        master:
            driverClass: com.mysql.jdbc.Driver
            url: jdbc:mysql://127.0.0.1/xinqch_master?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull
            username: root
            password: xinqch

         slave:
            driverClass: com.mysql.jdbc.Driver
            url: jdbc:mysql://127.0.0.1/xinqch_slave?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull
            username: root
            password: xinqch



